### ISSUE TITLE
[python 3] 설치 과정 중 jnius의 Class not found b'kr/bydelta/koala/POS'

### ISSUE THREAD

**Issue by full-kim** [koalanlp/koalanlp#23]
### 기초정보
- KoalaNLP 버전은 얼마였나요? 2.0.6
- 어떤 프로그래밍 언어에서 문제가 생겼습니까? ([]안에 x표하여 표기해주세요)
  - [ ] Kotlin
  - [ ] Java
  - [ ] Scala
  - [x] Python 3 +
  - [ ] 기타 JVM 계열 언어
- 문제의 유형은 어떤 것인가요?
  - [ ] 버그리포트
  - [ ] 개선점제안
  - [ ] 사용법질문
  - [x] 기타

### 재연을 위한 정보
Python 3+ 설치 소개 문서에서 안내해 주신 바와 같이 
Cython, koalanlp를 오류 없이 설치하고 아래 과정을 진행하였습니다.

from koalanlp.Util import initialize
initialize(java_options="-Xmx4g", KKMA="2.0.4", ETRI="2.0.4")

### 본문
- 그 결과 Class not found b'kr/bydelta/koala/POS' 라는 JavaException이 나타났습니다.

아래는 오류의 전체 내용입니다.

C:\anaconda64bit\lib\site-packages\koalanlp\Util.py in initialize(java_options, **packages)
    184
    185         # Enum 항목 초기화
--> 186         POS.values()
    187         PhraseTag.values()
    188         DependencyTag.values()

C:\anaconda64bit\lib\site-packages\koalanlp\types.py in values()
     46         """
     47         if len(POS.__VALUES__) == 0:
---> 48             POS.__VALUES__ = _enum_value_dict(__class__.__name__, lambda x: POS(x))
     49             for name, value in POS.__VALUES__.items():
     50                 setattr(POS, name, value)

C:\anaconda64bit\lib\site-packages\koalanlp\types.py in _enum_value_dict(cls, item_converter)
      6
      7 def _enum_value_dict(cls, item_converter):
----> 8     return {value.name: value for value in py_list(koala_class_of(cls).values(), item_converter)}
      9
     10

C:\anaconda64bit\lib\site-packages\koalanlp\jnius.py in koala_class_of(*path)
     18
     19 def koala_class_of(*path):
---> 20     return class_of('kr.bydelta.koala', *path)
     21
     22

C:\anaconda64bit\lib\site-packages\koalanlp\jnius.py in class_of(*path)
     12     if path not in _CLASS_DIC:
     13         print(path)
---> 14         _CLASS_DIC[path] = autoclass(path)
     15
     16     return _CLASS_DIC[path]

C:\anaconda64bit\lib\site-packages\jnius\reflect.py in autoclass(clsname)
    157
    158     # c = Class.forName(clsname)
--> 159     c = find_javaclass(clsname)
    160     if c is None:
    161         raise Exception('Java class {0} not found'.format(c))

jnius\jnius_export_func.pxi in jnius.find_javaclass()

JavaException: Class not found b'kr/bydelta/koala/POS'

혹시 이 부분은 어떻게 해결해야할지 여쭤보고 싶습니다.

감사합니다.

**Comment by nearbydelta** [comment]
안녕하세요, full-kim님.
윈도 환경 구성하고 테스트 진행해보느라고 좀 늦어졌습니다.
KoalaNLP는 Python에서도 Java로 구현된 부분을 불러와 사용하기 때문에, 웹에서 필요한 파일을 다운로드 하게 됩니다.
`Class not found` 문제는 Java 구현체가 깨져있어서 다시 다운로드가 필요한 경우입니다.
그래서 해당 파일을 찾아 삭제하시고 다시 초기화해주시면 문제가 해결될 것 같습니다.

다운로드 된 파일은 python 프로그램을 실행중인 위치 하위에 `.jip` 폴더로 위치합니다.
문제가 되고 있는 파일은 koalanlp-core 파일이고, 아마 다음 위치에 있을겁니다.
```
.jip\cache\kr.bydelta\koalanlp-core
```
해당 폴더에 포함된 파일을 모두 삭제하시고 다시 돌려보신 다음 문제가 해결되었는지 알려주시면 감사하겠습니다.
이후 구현에서는 이를 자동으로 체크해서 필요한 라이브러리를 다시 받도록 처리해야겠네요...

혹시 도움이 되셨을까요?

**Comment by chanhopark00** [comment]
안녕하세요. 저 또한 같은 문제에 봉착해서 글 남기게 되었습니다.
말씀하신대로 .jip\cache\kr.bydelta\koalanlp-core에 있는 파일을 모두 삭제하고 다시 돌려보았을때 같은 에러가 뜹니다. 혹시 다른 방법은 어떤게 있을까요 ?

**Comment by nearbydelta** [comment]
@chanhopark00 문제를 재현해볼 수 있도록 다음 정보를 알 수 있을까요?
- 사용 중인 운영체제 및 버전:
- 사용 중인 자바 JDK 버전:
- 사용 중인 파이썬 버전:
- 시도한 initialize 코드:

**Comment by chanhopark00** [comment]
운영체제 Windows 10, 64-bit
JDK 버젼: jdk1.8.0_211
파이썬 버젼: Python 3.6.7
initialize 코드: -Xmx4g 

Readme에 있는 코드를 실행해보았을때 생긴 에러가 위에 질문하신분 에러와 동일합니다!

**Comment by nearbydelta** [comment]
@chanhopark00 
같은 환경 구성해서 실행하고 나서 깨달았는데 README에 주의사항을 넣지 않았네요..
initialize code에는 반드시 패키지를 하나 이상 지정하셔야 합니다.
해당 사항 체크하도록 추가해서 버전업하도록 하겠습니다.

다음 코드는 같은 환경[JDK 1.8.0_211 64bit, 파이썬 3.6.7 64bit]에서 정상 작동하는 것 확인했습니다:
```python
from koalanlp.Util import initialize

# 꼬꼬마와 ETRI 분석기의 2.0.4 버전을 참조합니다.
initialize(java_options="-Xmx4g", KKMA="2.0.4", ETRI="2.0.4")
```python

**Comment by nearbydelta** [comment]
@chanhopark00 @full-kim
2.0.7에서 초기화시 기본값 확인하도록 추가하였습니다.
테스트 코드로도 문제가 없긴 하였지만, 다른 환경에서 테스트하면 다른 문제가 발생할지도 모르니,
문제가 혹시 해결되는지 확인해주실 수 있을까요?

**Comment by chanhopark00** [comment]
저의 경우에는 해결되었습니다!
그리고 이것저것 시도해보던중 JAVA_HOME 설정을 다음과같은 방법으로 하였을때 해결된것 같기도 하네요. 

import os 
 def install_java():
   # linux command before running
   # apt-get install -y openjdk-8-jdk-headless -qq > /dev/null  
   os.environ["JAVA_HOME"] = "/usr/lib/jvm/java-11-openjdk-amd64/"     #set environment variable

install_java()

# initialize(java_options="-Xmx4g -Dfile.encoding=utf-8", KKMA="2.0.2",RHINO="2.0.5", EUNJEON="2.0.2", ETRI="2.0.2")
