### ISSUE TITLE
초기화 때 필수 파일들 다우로드 안 됨

### ISSUE THREAD

**Issue by tdplaza** [koalanlp/koalanlp#26]
문장단위로 분리 하고 싶어서 python 3.6, Koalanlp 2.1.3 사용하려고 하는 데요,

근데 `sentencesplitter(api=API.HNN)` 명령 실행 하면 초기화 필요라는 문제가 나옵니다. 

초기화 하려고 해서 
```
from koalanlp.Util import initialize
	initialize(hnn='LATEST')
```
 실행해보니까 여리 필수 library를 못 찾다는 에러가 나옵니다.

![image](https://user-images.githubusercontent.com/31118781/72503694-b95b6c80-387f-11ea-969f-b2d57f75d2d7.png)

이 문제를 해결 방안 있거나 필수 librarires 좀 공유 해주시면 감사드리겠습니다. 

전체 코드를 아래와 같습니다. 
![image](https://user-images.githubusercontent.com/31118781/72503947-371f7800-3880-11ea-974f-b7a783ada6df.png)

감사합니다.

**Comment by nearbydelta** [comment]
늦어서 죄송합니다.

2020년부터 대부분의 Repo가 HTTPS만 지원하게 되어서 HTTP로 하면 다운로드에 문제가 발생합니다.
또한 최신 버전을 확인하는 코드 역시 영향을 받아, 수정되었으니 Python KoalaNLP는 2.1.4 이후 버전을 사용해주시면 감사하겠습니다. 상세한 사항은 koalanlp/python-support@2da711b commit을 참조하세요.
