### ISSUE TITLE
초기화 오류

### ISSUE THREAD

**Issue by ldahee** [koalanlp/koalanlp#27]
### 기초정보
- KoalaNLP 버전은 얼마였나요? 
  2.1.3
- 어떤 프로그래밍 언어에서 문제가 생겼습니까? ([]안에 x표하여 표기해주세요)
  - [ ] Kotlin
  - [ ] Java
  - [ ] Scala
  - [ ] 기타 JVM 계열 언어
  - [x] Python 
- 문제의 유형은 어떤 것인가요?
  - [x] 버그리포트
  - [ ] 개선점제안
  - [ ] 사용법질문
  - [ ] 기타

### 재연을 위한 정보
- 어떤 문장을 시도하셨습니까?
```text
[여기에 문장을 넣어주세요]
```
- KoalaNLP를 사용한 코드 부분을 보여주세요.
```Python
// 여기에 사용한 코드부분을 보여주세요. 윗줄에 'kotlin'라고 되어있는 언어유형을 사용중인 언어로 바꾸는것을 권합니다.
from koalanlp.Util import initialize, finalize
from koalanlp.proc import Parser
from koalanlp import API

initialize(KKMA='2.0.2')
finalize()
```

### 본문
- 아래에 본문을 입력해주세요.
위의 코드를 실행하면 아래와 같은 오류가 뜹니다.
![그림1](https://user-images.githubusercontent.com/41093239/73730442-19a44680-477a-11ea-8dec-3864af2358ea.png)

**Comment by ldahee** [comment]
해결했습니다!
혹시 같은 문제 겪는 분들 계실까봐 올려요.
koalanlp/Util.py에서 아래와 같이 http를 https로 수정하면 됩니다.
![캡처](https://user-images.githubusercontent.com/41093239/73921515-d6c5a880-490a-11ea-8d0f-2c2b76e804d5.PNG)

**Comment by sechan-hwang** [comment]
@ldahee 덕분에 해결했습니다.~ 감사합니다.^^

**Comment by ldahee** [comment]
도움이 되셨다니 다행입니다!
좋은 하루 되세요~
 
-----Original Message-----

**Comment by nearbydelta** [comment]
늦어서 죄송합니다. @ldahee 님과 @jihunchoi 님의 도움으로 문제를 2.1.4버전부터 수정하였습니다.

2020년부터 대부분의 Repo가 HTTPS만 지원하게 되어서 HTTP로 하면 다운로드에 문제가 발생합니다.
또한 최신 버전을 확인하는 코드 역시 영향을 받아, 수정되었으니 Python KoalaNLP는 2.1.4 이후 버전을 사용해주시면 감사하겠습니다. 상세한 사항은 https://github.com/koalanlp/python-support/commit/2da711b29c445535f0c7a93b2e456f4f0a77182c commit을 참조하세요.
