### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'khaiii' 에러 발생

### ISSUE THREAD

**Issue by youhyun97** [koalanlp/koalanlp#30]
### 기초정보
- KoalaNLP 버전은 얼마였나요? 
2.1.4
- 어떤 프로그래밍 언어에서 문제가 생겼습니까? ([]안에 x표하여 표기해주세요)
  - [ ] Kotlin
  - [x] Java
  - [ ] Scala
  - [ ] 기타 JVM 계열 언어
- 문제의 유형은 어떤 것인가요?
  - [x] 버그리포트
  - [ ] 개선점제안
  - [x] 사용법질문
  - [ ] 기타

### 재연을 위한 정보
- khaiii 실행시에 문제가 생깁니다.
`Exception in thread "main" java.lang.UnsatisfiedLinkError: Unable to load library 'khaiii'`

- KoalaNLP를 사용한 코드 부분을 보여주세요.
Java 코드입니다.
<img width="1768" alt="스크린샷 2021-06-24 오후 1 40 54" src="https://user-images.githubusercontent.com/37606785/123211448-708cf600-d4fe-11eb-9f86-37391eb89ab9.png">

pom.xml 코드입니다.
<img width="759" alt="스크린샷 2021-06-24 오후 1 48 05" src="https://user-images.githubusercontent.com/37606785/123208623-6bc64300-d4fa-11eb-8e83-e5e4264a0355.png">

그리고, 현재 macOS 에서 진행중인데, prok.kt를 보니, LD_LIBRARY_PATH와 같은 환경변수를 등록하라고 하셔서 
`export DYLD_LIBRARY_PATH=/usr/local/share/khaiii` 와 같이 등록해주었지만 여전히 같은 에러가 발생합니다.

### 본문
- khaiii를 실행하는데 위와 같은 문제가 발생합니다. 혹시 이와 관련되어 도움을 주실 수 있을까요? 감사합니다! :)

**Comment by bgnkim** [comment]
혹시 Khaiii 별도 설치는 완료 하셨나요?

**Comment by youhyun97** [comment]
안녕하세요!
khaiii 별도 설치 후, darwin 디렉터리를 만들어 libkhaiii.dylib를 직접 복사해 넣었더니 되었습니다..!ㅎㅎ

2021년 7월 5일 (월) 오전 10:28, Bugeun Kim ***@***.***>님이 작성:
